### PR TITLE
Create index.html

### PR DESCRIPTION
**Pull request by narcher2**

### CODE REVIEW

**Comment by EduApps-CDG** [comment]
the site doesn't work because the index doesn't exists

**Comment by RSamaium** [comment]
Version 2 being obsolete. I close the ticket.

Feel free to use version 3. Thank you!

**Comment by EduApps-CDG** [comment]
we already have a documentation?

**Comment by RSamaium** [comment]
Yes, there are still parts to finish. But there are already a lot of things to create a game

https://docs.rpgjs.dev

**Comment by EduApps-CDG** [comment]
Nice

**Pull request closed without merging**
